### ISSUE TITLE
geoMap library

### ISSUE THREAD

**Issue by agrignard** [obsa-and/SolarScope#2]
I am trying to make run the script 

after installing geomap I still have an error

SolarScope
Table attributes = geoMap.getAttributeTable();

getAttributeTable doesn't exist, I install the library from Processing do I have to use another one?

If yes do you have it?

**Comment by markusand** [comment]
getAttributeTable is a method in geoMap library, if it doesn’t find it you may have not properly installed the library or missing to include it somewhere

**Comment by agrignard** [comment]
yep the library that you can get from processing is not the right one

I installed directly this one https://www.gicentre.net/geomap/ and then it's ok
